@echo off
REM Remove AppX packages
powershell -Command "Get-AppxPackage 'Clipchamp.Clipchamp_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.BingNews_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.BingSearch_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.BingWeather_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.GetHelp_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.MicrosoftOfficeHub_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.MicrosoftSolitaireCollection_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.MicrosoftStickyNotes_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.OutlookForWindows_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.Paint_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.PowerAutomateDesktop_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.Todos_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.Windows.DevHome_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.WindowsAlarms_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.WindowsFeedbackHub_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.WindowsSoundRecorder_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.WindowsTerminal_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.XboxSpeechToTextOverlay_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.YourPhone_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'Microsoft.ZuneMusic_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'MicrosoftCorporationII.MicrosoftFamily_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'MicrosoftCorporationII.QuickAssist_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'MSTeams_*' | Remove-AppxPackage"
powershell -Command "Get-AppxPackage 'MicrosoftWindows.Client.WebExperience_*' | Remove-AppxPackage"
